### ISSUE TITLE
RMSD does not seem to be correct

### ISSUE THREAD

**Issue by LilySnow** [X-lab-3D/GradPose#16]
The RMSD values from calc_rmsd_with_template() do not seem to be correct… Did you compare with pdb2sql or ProFit on several cases?

Here is my command:

`python gradpose.py -i ../../examples/PDBs/  -c M -r 1:180 -n 4  --rmsd --verbose`

The rmsd that I got:

Template	../../examples/1AGD_template.pdb
1AGD.pdb	6.817497915769525e-07
1LP9.pdb	16.12244573923463
2H6P.pdb	15.130915326196774
3PWL.pdb	14.935339291532562
4G42.pdb	117.51142120491433
5C0A.pdb	14.87346804143781
5TEZ.pdb	19.270347212921646
6KWN.pdb	24.042137062836726
6ULR.pdb	122.4421570612006
7LG0.pdb	22.45569173016011

Some of these RMSDs are extremely high considering that the  resulting structures are very well aligned. 

I remember Farzaneh and Jan compared the RMSDs that Kevin calculated with pdb2sql. And they were fine...

**Comment by LilySnow** [comment]
After you fix this bug, please add a test on the RMSD

**Comment by DTRademaker** [comment]
After investigating further, we found that the issue was caused by using the standardized coordinates of the 3D structures. We have since fixed this issue by using unscaled values, and the RMSD values are now correct. In our paper, we utilized a third-party software for the calculations in order to ensure a fair comparison between different software tools. This is the reason why the issue went unnoticed during our analysis.
